module.exports = {
    angular: {
        files: [{
            expand: true,
            src: "**",
            cwd: 'bower_components/bootstrap/fonts',
            dest: "angular/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'bower_components/font-awesome/fonts',
            dest: "angular/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'bower_components/Simple-Line-Icons/fonts',
            dest: "angular/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'app/fonts',
            dest: "angular/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'app/l10n',
            dest: "angular/l10n"
        }, {
            expand: true,
            src: "**",
            cwd: 'app/img',
            dest: "angular/img"
        }, {
            expand: true,
            src: "**",
            cwd: 'app/js',
            dest: "angular/js"
        }, {
            expand: true,
            src: "**",
            cwd: 'app/tpl',
            dest: "angular/tpl"
        }, {
            src: 'app/index.min.html',
            dest: 'angular/index.html'
        }]
    },
    html: {
        files: [{
            expand: true,
            src: "**",
            cwd: 'bower_components/bootstrap/fonts',
            dest: "html/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'bower_components/font-awesome/fonts',
            dest: "html/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'bower_components/Simple-Line-Icons/fonts',
            dest: "html/fonts"
        }, {
            expand: true,
            src: '**',
            cwd: 'app/fonts/',
            dest: 'html/fonts/'
        }, {
            expand: true,
            src: '**',
            cwd: 'app/img/',
            dest: 'html/img/'
        }, {
            expand: true,
            src: '*.css',
            cwd: 'app/css/',
            dest: 'html/css/'
        }, {
            expand: true,
            src: '**',
            cwd: 'swig/js/',
            dest: 'html/js/'
        }]
    },
    landing: {
        files: [{
            expand: true,
            src: "**",
            cwd: 'bower_components/bootstrap/fonts',
            dest: "landing/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'bower_components/font-awesome/fonts',
            dest: "landing/fonts"
        }, {
            expand: true,
            src: "**",
            cwd: 'bower_components/Simple-Line-Icons/fonts',
            dest: "landing/fonts"
        }, {
            expand: true,
            src: '**',
            cwd: 'app/fonts/',
            dest: 'landing/fonts/'
        }, {
            expand: true,
            src: '*.css',
            cwd: 'app/css/',
            dest: 'landing/css/'
        }, {
            src: 'html/css/app.min.css',
            dest: 'landing/css/app.min.css'
        }]
    }

};